# Generated by Django 3.1.3 on 2020-12-03 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_what_is'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='what_is',
            field=models.TextField(blank=True),
        ),
    ]
