# Generated by Django 3.1.3 on 2020-12-04 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_what_is'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='what_is',
        ),
    ]
